[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
clap = { version = "4.5.40", features = ["derive"] }
engine = { path = "../engine" }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
